eureka:
  client:
    service-url:
      defaultZone: http://eureka5:8761/eureka/, http://eureka6:8762/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: HcWl@8888
    url: jdbc:mysql://rm-wz93m6g398fof75c5.mysql.rds.aliyuncs.com:3306/cloud_pay_hc?characterEncoding=utf-8&useSSL=false&autoReconnect=true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

logging:
  level:
    com.cloud.agent.dao: error
    org.springframework.cloud.netflix.feign: error