eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud_pay?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    secondary:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

logging:
  level:
    com.cloud.sysuser: debug
    org.springframework.cloud.netflix.feign: debug