eureka:
  client:
    service-url:
      defaultZone: http://eureka3:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60
  server:
    enable-self-preservation: false
    peerEurekaNodesUpdateIntervalMs: 60000
  instance:
    prefer-ip-address: true
    hostname: eureka4
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: eureka4
server:
  port: 8762
